name: flutter_with_supabase
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1
  
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  go_router: ^14.6.3
  logger: ^2.5.0
  path: ^1.9.0
  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.0.17
  intl: ^0.20.1
  url_launcher: ^6.3.1
  flutter_easyloading: ^3.0.5
  flutter_spinkit: ^5.2.1
  flutter_riverpod: ^2.6.1
  supabase_flutter: ^2.8.3
  connectivity_plus: ^6.1.2
  fast_cached_network_image: ^1.2.9

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^5.0.0
  
flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - .env  

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
